version: "3.1"
services:
# DATABASE *****************************************
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=123
         - POSTGRES_USER=postgres
         - POSTGRES_DB=store
    restart: unless-stopped
# API REST *****************************************
  store:
    image: store:latest
    network_mode: bridge
    container_name: store
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data:      